# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/fit21
#     username: postgres
#     password: postgres
#     driver-class-name: org.postgresql.Driver
#   jpa:
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true

#   flyway:
#     enabled: false

# server:
#   port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update  # <-- ESSA LINHA CRIA AS TABELAS
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true